

name: Node.js CI

on:
  push:
    branches: [ "main" ]


jobs:
  compile:

    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: set Node.js 
      uses: actions/setup-node@v4
      with:  
        node-version: "23"
        
    - name: Frontend compilation (Syntax check)
      run: |
        cd src
        find . -name "*.js" -exec node --check {} +
        
  gitleaks-sacns:
    runs-on: ubuntu-latest


    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: gitleaks setup 
      uses: gitleaks/gitleaks-action@v2

    - name: gitleaks scan
      run: |
        gitleaks detect --source . --exit-code 1
        
    
      
      
    
    
  
    
